#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server
if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    path_to_file=$1;
    ip_address=$2;
    username=$3;
    ssh_path=$4;
    scp -i "$ssh_path" -o StrictHostKeyChecking=no "$path_to_file" "$username@$ip_address:~/";
fi
