#!/usr/bin/env bash
# This script pings an IP address passed as an argument.

if [ $# != 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

ip_address=$1
i=0
while ((i < 5)); do
    ping -c 1 "$ip_address"
    ((i++))
done
