#!/usr/bin/env bash
# This script displays:
	# To infinity and beyond indefinitely
	# With a sleep 2 in between each iteration
	# I am invincible!!! when receiving a SIGTERM signal

signal_status=""
trap 'signal_status="SIGTERM"' SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
	if [ "$signal_status" = "SIGTERM" ]; then
        echo "I am invincible!!!"
		signal_status=""
    fi
done